@NoteAssistant.KnowledgeGraph.Backend_HostAddress = http://localhost:5070

POST {{NoteAssistant.KnowledgeGraph.Backend_HostAddress}}/api/query/assist
Content-Type: application/json

{
  "prompt": "show all chunks and entities"
}

###

POST {{NoteAssistant.KnowledgeGraph.Backend_HostAddress}}/api/query
Content-Type: application/json

{
  "graphName": "knowledge_graph",
  "cypher": "MATCH p=(n)-[r]->(m) RETURN n, r, m LIMIT 10"
}
